### ISSUE TITLE
Is there a demo of run a ftp server which support for local file system?

### ISSUE THREAD

**Issue by nifflin** [fclairamb/ftpserverlib#73]
Thank you.

**Comment by fclairamb** [comment]
That's precisely how it currently works. You can just start it with:
```bash
./ftpserver -data /tmp
```
And then when you login with the `test`/`test` credentials, your file will appear in `/tmp/shared`.

And that's because the default setup contains this part:
```toml
[[users]]
user="test"
pass="test"
dir="shared"
```
